version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.9.7-management
    restart: always
    hostname: rabbitmq
    networks:
      - rabbitmq-test
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq

volumes:
  rabbitmq-volume:

networks:
  rabbitmq-test: